sudo: required

language: python
python:
  - 2.7
  - 3.5
  - 3.6

env:
  - NGINX_CONFIG=basic
  - NGINX_CONFIG=port_number

install:
  - sudo apt-get install nginx
  - sudo service nginx start
  - pip install -r requirements.txt

script:
  - sudo cp configs/$NGINX_CONFIG /etc/nginx/sites-available
  - sudo ln -s /etc/nginx/sites-available/$NGINX_CONFIG /etc/nginx/sites-enabled
  - sudo nginx -t
  - sudo service nginx restart
  - nohup python app.py &
  - python -m unittest test.live_test_$NGINX_CONFIG

notifications:
  email: false